import Fastify from 'fastify';
import cors from '@fastify/cors';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import { config } from './config/index.js';

const fastify = Fastify({
  logger: {
    level: config.logLevel,
    transport: config.nodeEnv === 'development' ? {
      target: 'pino-pretty',
      options: {
        colorize: true,
        translateTime: 'HH:MM:ss Z',
        ignore: 'pid,hostname',
      },
    } : undefined,
  },
});

// CORS enabled for dev proxy - allows frontend on different port
await fastify.register(cors, {
  origin: config.corsOrigin,
  credentials: true,
});

await fastify.register(swagger, {
  swagger: {
    info: {
      title: 'GIRA Raw Data → Control Dashboard API',
      description: 'API generated by Architect Studio',
      version: '1.0.0',
    },
    host: `localhost:${config.port}`,
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
      bearerAuth: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header',
      },
    },
  },
});

await fastify.register(swaggerUi, {
  routePrefix: '/docs',
  uiConfig: {
    docExpansion: 'list',
    deepLinking: false,
  },
});

// Health check endpoint (matches OpenAPI spec)
fastify.get('/api/v1/health', async (request, reply) => {
  return {
    status: 'ok',
    timestamp: new Date().toISOString(),
    version: '1.0.0',
  };
});

// Root endpoint
fastify.get('/', async (request, reply) => {
  return {
    message: 'GIRA Raw Data → Control Dashboard API',
    docs: '/docs',
    health: '/api/v1/health',
  };
});

// Stub endpoints for entities defined in OpenAPI spec
// These return mock data - replace with real DB queries later

const entities = ['users', 'accounts', 'profiles', 'settings', 'tasks', 'items', 'projects', 'categories', 'tags', 'lists', 'teams', 'organizations', 'notifications', 'messages'];

for (const entity of entities) {
  // List endpoint
  fastify.get(`/api/v1/${entity}`, async (request, reply) => {
    const query = request.query as { page?: number; pageSize?: number };
    return {
      data: [],
      pagination: {
        page: query.page || 1,
        pageSize: query.pageSize || 20,
        total: 0,
        totalPages: 0,
      },
    };
  });

  // Get by ID
  fastify.get(`/api/v1/${entity}/:id`, async (request, reply) => {
    const { id } = request.params as { id: string };
    reply.code(404);
    return { error: 'Not found', message: `${entity} with id ${id} not found` };
  });

  // Create
  fastify.post(`/api/v1/${entity}`, async (request, reply) => {
    reply.code(501);
    return { error: 'Not implemented', message: `Create ${entity} not yet implemented` };
  });

  // Update
  fastify.put(`/api/v1/${entity}/:id`, async (request, reply) => {
    reply.code(501);
    return { error: 'Not implemented', message: `Update ${entity} not yet implemented` };
  });

  // Delete
  fastify.delete(`/api/v1/${entity}/:id`, async (request, reply) => {
    reply.code(501);
    return { error: 'Not implemented', message: `Delete ${entity} not yet implemented` };
  });
}

export { fastify };
