// This file will be auto-generated by running: npm run generate-api-types
// Run that command after the backend is running to generate types from OpenAPI spec

// Placeholder types until generation
export interface paths {
  '/api/v1/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string
              timestamp: string
              version: string
            }
          }
        }
      }
    }
  }
  '/api/v1/users': {
    get: {
      parameters: {
        query?: {
          page?: number
          pageSize?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': {
              data: any[]
              pagination: {
                page: number
                pageSize: number
                total: number
                totalPages: number
              }
            }
          }
        }
      }
    }
  }
  // TODO: Add more endpoints after running generate-api-types
}

export type components = {
  schemas: {
    HealthCheck: {
      status: string
      timestamp: string
      version: string
    }
    // TODO: Add more schemas after running generate-api-types
  }
}
